spring:
  application:
    name: auction-service
  profiles:
    active: none
  config:
    import: ${CONFIG_SERVER_URL}

  cloud:
    config:
      profile: ${PROFILE}

encrypt:
  key: ${ENCRYPT_KEY}